function out1 = odefunc(in1)
%ODEFUNC
%    OUT1 = ODEFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-Oct-2017 11:04:14

x = in1(:,1);
y = in1(:,2);
out1 = [y,-x-y.*(x.^2.*5.0-5.0)];
