function xNext = xNextFileIRK1(t,in2,in3,dt)
%XNEXTFILEIRK1
%    XNEXT = XNEXTFILEIRK1(T,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    17-Oct-2017 11:04:12

K1_1 = in3(1);
K1_2 = in3(3);
K2_1 = in3(2);
K2_2 = in3(4);
x1 = in2(1,:);
x2 = in2(2,:);
xNext = [x1+K1_1.*dt.*(1.0./2.0)+K2_1.*dt.*(1.0./2.0);x2+K1_2.*dt.*(1.0./2.0)+K2_2.*dt.*(1.0./2.0)];
